export type VisaDocumentReviewStatus = "PENDING" | "APPROVED" | "REJECTED";

export interface RequiredDocumentField {
  key: string;
  labelKo: string;
  labelEn: string;
  required: boolean;
}

export interface VisaDocumentRequirementSeed {
  code: string;
  visaType: string;
  stayAction: "issuance" | "extension" | "change" | "permanent_residence";
  applicantContext: string;
  documentType: string;
  labelKo: string;
  labelEn: string;
  required: boolean;
  validityDays: number | null;
  issuer: string;
  requiredFields: RequiredDocumentField[];
  validationRules: string[];
  sourceRefs: string[];
  sourceUrl: string;
  sourceType: "official_government" | "official_law" | "internal_analysis";
  lastCheckedAt: string;
  checkedBy: string;
  reviewStatus: VisaDocumentReviewStatus;
  notes?: string;
}

const CHECKED_BY = "phase0_seed_unreviewed";
const LAST_CHECKED_AT = "2026-07-03";
const LAW_ATTACHMENTS = "immigration-rule-documents-attachments";
const LAW_STATUS_TABLE = "immigration-decree-long-term-status-table";
const HIKOREA_MANUAL = "hikorea-d2-d4-d10-e7-f2-f5-requirements";
const HIKOREA_FORMS = "hikorea-forms-document-checklist";
const STUDY_DOCS = "studyinkorea-visa-documents";
const VISA_PORTAL = "visa-portal-visa-types";
const POSITIVE_NUMERIC_FIELD_KEYS = new Set(["balance", "paid_amount", "income_amount", "wage"]);
const PERCENTAGE_FIELD_KEYS = new Set(["attendance_rate"]);

function field(key: string, labelKo: string, labelEn: string, required = true): RequiredDocumentField {
  return { key, labelKo, labelEn, required };
}

function rulesFor(fields: RequiredDocumentField[], validityDays: number | null, extras: string[] = []): string[] {
  const requiredKeys = new Set(fields.filter((item) => item.required).map((item) => item.key));
  return [
    "required_document_present",
    "issuer_present",
    ...fields.filter((item) => item.required).map((item) => `field:${item.key}:present`),
    ...[...requiredKeys]
      .filter((key) => POSITIVE_NUMERIC_FIELD_KEYS.has(key))
      .map((key) => `numeric_positive:${key}`),
    ...[...requiredKeys]
      .filter((key) => PERCENTAGE_FIELD_KEYS.has(key))
      .map((key) => `numeric_range:${key}:0:100`),
    ...(validityDays ? [`issue_date_within:${validityDays}:days`] : []),
    ...extras,
  ];
}

function req(input: Omit<VisaDocumentRequirementSeed, "checkedBy" | "lastCheckedAt" | "reviewStatus" | "validationRules" | "required" | "sourceType"> & {
  required?: boolean;
  sourceType?: VisaDocumentRequirementSeed["sourceType"];
  validationRules?: string[];
}): VisaDocumentRequirementSeed {
  const required = input.required ?? true;
  return {
    ...input,
    required,
    sourceType: input.sourceType || "official_government",
    checkedBy: CHECKED_BY,
    lastCheckedAt: LAST_CHECKED_AT,
    reviewStatus: "PENDING",
    validationRules: input.validationRules || rulesFor(input.requiredFields, input.validityDays),
  };
}

const common = {
  lawAndManual: [LAW_STATUS_TABLE, LAW_ATTACHMENTS, HIKOREA_MANUAL],
  formsAndManual: [LAW_ATTACHMENTS, HIKOREA_FORMS, HIKOREA_MANUAL],
  studyAndLaw: [LAW_STATUS_TABLE, LAW_ATTACHMENTS, STUDY_DOCS],
};

export const VISA_DOCUMENT_REQUIREMENT_SEEDS: VisaDocumentRequirementSeed[] = [
  req({
    code: "d2_issuance_passport",
    visaType: "D-2",
    stayAction: "issuance",
    applicantContext: "general",
    documentType: "passport",
    labelKo: "여권",
    labelEn: "Passport",
    validityDays: null,
    issuer: "applicant_home_country",
    requiredFields: [
      field("passport_no", "여권번호", "Passport number"),
      field("full_name", "성명", "Full name"),
      field("birth_date", "생년월일", "Date of birth"),
      field("expiry_date", "만료일", "Expiry date"),
    ],
    sourceRefs: common.studyAndLaw,
    sourceUrl: "https://www.studyinkorea.go.kr",
  }),
  req({
    code: "d2_issuance_visa_application_form",
    visaType: "D-2",
    stayAction: "issuance",
    applicantContext: "general",
    documentType: "visa_application_form",
    labelKo: "사증발급신청서",
    labelEn: "Visa application form",
    validityDays: null,
    issuer: "applicant",
    requiredFields: [
      field("full_name", "성명", "Full name"),
      field("nationality", "국적", "Nationality"),
      field("passport_no", "여권번호", "Passport number"),
      field("contact", "연락처", "Contact"),
    ],
    sourceRefs: [LAW_ATTACHMENTS, STUDY_DOCS],
    sourceUrl: "https://www.studyinkorea.go.kr",
  }),
  req({
    code: "d2_issuance_photo",
    visaType: "D-2",
    stayAction: "issuance",
    applicantContext: "general",
    documentType: "photo",
    labelKo: "표준 사진",
    labelEn: "Standard photo",
    validityDays: 180,
    issuer: "applicant",
    requiredFields: [field("photo_standard", "사진 규격", "Photo specification")],
    sourceRefs: [LAW_ATTACHMENTS, STUDY_DOCS],
    sourceUrl: "https://www.studyinkorea.go.kr",
  }),
  req({
    code: "d2_issuance_standard_admission_letter",
    visaType: "D-2",
    stayAction: "issuance",
    applicantContext: "degree",
    documentType: "standard_admission_letter",
    labelKo: "표준입학허가서",
    labelEn: "Standard admission letter",
    validityDays: null,
    issuer: "receiving_university",
    requiredFields: [
      field("student_name", "학생 성명", "Student name"),
      field("school_name", "학교명", "School name"),
      field("program", "과정", "Program"),
      field("admission_period", "입학 기간", "Admission period"),
    ],
    sourceRefs: common.studyAndLaw,
    sourceUrl: "https://www.studyinkorea.go.kr",
  }),
  req({
    code: "d2_issuance_final_education_certificate",
    visaType: "D-2",
    stayAction: "issuance",
    applicantContext: "degree",
    documentType: "final_education_certificate",
    labelKo: "최종학력 입증서류",
    labelEn: "Final education certificate",
    validityDays: null,
    issuer: "previous_school_or_authority",
    requiredFields: [
      field("student_name", "학생 성명", "Student name"),
      field("school_name", "학교명", "School name"),
      field("graduation_date", "졸업일", "Graduation date"),
    ],
    sourceRefs: common.studyAndLaw,
    sourceUrl: "https://www.studyinkorea.go.kr",
  }),
  req({
    code: "d2_issuance_transcript",
    visaType: "D-2",
    stayAction: "issuance",
    applicantContext: "degree",
    documentType: "transcript",
    labelKo: "성적증명서",
    labelEn: "Transcript",
    validityDays: null,
    issuer: "previous_school",
    requiredFields: [
      field("student_name", "학생 성명", "Student name"),
      field("school_name", "학교명", "School name"),
      field("grades", "성적", "Grades"),
    ],
    sourceRefs: [LAW_ATTACHMENTS, STUDY_DOCS],
    sourceUrl: "https://www.studyinkorea.go.kr",
  }),
  req({
    code: "d2_issuance_financial_proof",
    visaType: "D-2",
    stayAction: "issuance",
    applicantContext: "degree",
    documentType: "financial_proof",
    labelKo: "재정능력 입증서류",
    labelEn: "Financial proof",
    validityDays: 90,
    issuer: "bank_or_sponsor",
    requiredFields: [
      field("holder_name", "예금주", "Account holder"),
      field("balance", "잔액", "Balance"),
      field("issue_date", "발급일", "Issue date"),
      field("currency", "통화", "Currency"),
    ],
    sourceRefs: common.studyAndLaw,
    sourceUrl: "https://www.studyinkorea.go.kr",
    notes: "Validity and balance thresholds vary by mission and program; legal reviewer must confirm before approval.",
  }),
  req({
    code: "d2_issuance_family_relation",
    visaType: "D-2",
    stayAction: "issuance",
    applicantContext: "sponsor_family",
    documentType: "family_relation",
    labelKo: "가족관계 입증서류",
    labelEn: "Family relationship proof",
    validityDays: 90,
    issuer: "civil_registry_or_public_authority",
    requiredFields: [
      field("applicant_name", "신청인", "Applicant"),
      field("sponsor_name", "보증인", "Sponsor"),
      field("relationship", "관계", "Relationship"),
    ],
    sourceRefs: [LAW_ATTACHMENTS, STUDY_DOCS],
    sourceUrl: "https://www.studyinkorea.go.kr",
  }),
  req({
    code: "d2_issuance_study_plan",
    visaType: "D-2",
    stayAction: "issuance",
    applicantContext: "degree",
    documentType: "study_plan",
    labelKo: "학업계획서",
    labelEn: "Study plan",
    validityDays: null,
    issuer: "applicant",
    requiredFields: [
      field("study_goal", "학업 목표", "Study goal"),
      field("program_fit", "과정 적합성", "Program fit"),
    ],
    sourceRefs: [STUDY_DOCS, VISA_PORTAL],
    sourceUrl: "https://www.studyinkorea.go.kr",
  }),
  req({
    code: "d2_issuance_language_proficiency",
    visaType: "D-2",
    stayAction: "issuance",
    applicantContext: "degree",
    documentType: "language_proficiency",
    labelKo: "한국어/영어 능력 증빙",
    labelEn: "Korean or English proficiency proof",
    validityDays: null,
    issuer: "topik_or_language_test_provider",
    requiredFields: [
      field("test_name", "시험명", "Test name"),
      field("score_or_level", "점수/등급", "Score or level"),
      field("test_date", "시험일", "Test date"),
    ],
    sourceRefs: [STUDY_DOCS, VISA_PORTAL],
    sourceUrl: "https://www.studyinkorea.go.kr",
  }),
  req({
    code: "d4_issuance_passport",
    visaType: "D-4",
    stayAction: "issuance",
    applicantContext: "language_training",
    documentType: "passport",
    labelKo: "여권",
    labelEn: "Passport",
    validityDays: null,
    issuer: "applicant_home_country",
    requiredFields: [
      field("passport_no", "여권번호", "Passport number"),
      field("full_name", "성명", "Full name"),
      field("expiry_date", "만료일", "Expiry date"),
    ],
    sourceRefs: common.studyAndLaw,
    sourceUrl: "https://www.studyinkorea.go.kr",
  }),
  req({
    code: "d4_issuance_application_form",
    visaType: "D-4",
    stayAction: "issuance",
    applicantContext: "language_training",
    documentType: "visa_application_form",
    labelKo: "사증발급신청서",
    labelEn: "Visa application form",
    validityDays: null,
    issuer: "applicant",
    requiredFields: [
      field("full_name", "성명", "Full name"),
      field("nationality", "국적", "Nationality"),
      field("passport_no", "여권번호", "Passport number"),
    ],
    sourceRefs: [LAW_ATTACHMENTS, STUDY_DOCS],
    sourceUrl: "https://www.studyinkorea.go.kr",
  }),
  req({
    code: "d4_issuance_photo",
    visaType: "D-4",
    stayAction: "issuance",
    applicantContext: "language_training",
    documentType: "photo",
    labelKo: "표준 사진",
    labelEn: "Standard photo",
    validityDays: 180,
    issuer: "applicant",
    requiredFields: [field("photo_standard", "사진 규격", "Photo specification")],
    sourceRefs: [LAW_ATTACHMENTS, STUDY_DOCS],
    sourceUrl: "https://www.studyinkorea.go.kr",
  }),
  req({
    code: "d4_issuance_admission_letter",
    visaType: "D-4",
    stayAction: "issuance",
    applicantContext: "language_training",
    documentType: "admission_letter",
    labelKo: "입학허가서",
    labelEn: "Admission letter",
    validityDays: null,
    issuer: "language_institute",
    requiredFields: [
      field("student_name", "학생 성명", "Student name"),
      field("institute_name", "교육기관명", "Institute name"),
      field("training_period", "연수 기간", "Training period"),
    ],
    sourceRefs: common.studyAndLaw,
    sourceUrl: "https://www.studyinkorea.go.kr",
  }),
  req({
    code: "d4_issuance_education_certificate",
    visaType: "D-4",
    stayAction: "issuance",
    applicantContext: "language_training",
    documentType: "education_certificate",
    labelKo: "최종학력 입증서류",
    labelEn: "Education certificate",
    validityDays: null,
    issuer: "previous_school_or_authority",
    requiredFields: [
      field("student_name", "학생 성명", "Student name"),
      field("school_name", "학교명", "School name"),
    ],
    sourceRefs: [LAW_ATTACHMENTS, STUDY_DOCS],
    sourceUrl: "https://www.studyinkorea.go.kr",
  }),
  req({
    code: "d4_issuance_financial_proof",
    visaType: "D-4",
    stayAction: "issuance",
    applicantContext: "language_training",
    documentType: "financial_proof",
    labelKo: "재정능력 입증서류",
    labelEn: "Financial proof",
    validityDays: 90,
    issuer: "bank_or_sponsor",
    requiredFields: [
      field("holder_name", "예금주", "Account holder"),
      field("balance", "잔액", "Balance"),
      field("issue_date", "발급일", "Issue date"),
    ],
    sourceRefs: common.studyAndLaw,
    sourceUrl: "https://www.studyinkorea.go.kr",
  }),
  req({
    code: "d4_issuance_training_plan",
    visaType: "D-4",
    stayAction: "issuance",
    applicantContext: "language_training",
    documentType: "training_plan",
    labelKo: "연수계획서",
    labelEn: "Training plan",
    validityDays: null,
    issuer: "language_institute_or_applicant",
    requiredFields: [
      field("training_goal", "연수 목적", "Training goal"),
      field("training_schedule", "연수 일정", "Training schedule"),
    ],
    sourceRefs: [STUDY_DOCS, VISA_PORTAL],
    sourceUrl: "https://www.studyinkorea.go.kr",
  }),
  req({
    code: "d4_issuance_tb_certificate",
    visaType: "D-4",
    stayAction: "issuance",
    applicantContext: "high_tb_nationality",
    documentType: "tuberculosis_certificate",
    labelKo: "결핵진단서",
    labelEn: "Tuberculosis certificate",
    validityDays: 90,
    issuer: "designated_medical_institution",
    requiredFields: [
      field("applicant_name", "신청인", "Applicant"),
      field("exam_date", "검진일", "Exam date"),
      field("result", "검진 결과", "Result"),
    ],
    sourceRefs: [LAW_ATTACHMENTS, STUDY_DOCS],
    sourceUrl: "https://www.studyinkorea.go.kr",
  }),
  req({
    code: "d2_extension_integrated_application",
    visaType: "D-2",
    stayAction: "extension",
    applicantContext: "general",
    documentType: "integrated_application_form",
    labelKo: "통합신청서",
    labelEn: "Integrated application form",
    validityDays: null,
    issuer: "applicant",
    requiredFields: [
      field("alien_registration_no", "외국인등록번호", "Alien registration number"),
      field("stay_action", "신청 업무", "Stay action"),
    ],
    sourceRefs: common.formsAndManual,
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "d2_extension_passport_arc",
    visaType: "D-2",
    stayAction: "extension",
    applicantContext: "general",
    documentType: "passport_arc",
    labelKo: "여권 및 외국인등록증",
    labelEn: "Passport and alien registration card",
    validityDays: null,
    issuer: "applicant_home_country_and_moj",
    requiredFields: [
      field("passport_no", "여권번호", "Passport number"),
      field("alien_registration_no", "외국인등록번호", "Alien registration number"),
    ],
    sourceRefs: common.formsAndManual,
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "d2_extension_enrollment_certificate",
    visaType: "D-2",
    stayAction: "extension",
    applicantContext: "degree",
    documentType: "enrollment_certificate",
    labelKo: "재학증명서",
    labelEn: "Certificate of enrollment",
    validityDays: 30,
    issuer: "university",
    requiredFields: [
      field("student_name", "학생 성명", "Student name"),
      field("school_name", "학교명", "School name"),
      field("enrollment_status", "재학 상태", "Enrollment status"),
    ],
    sourceRefs: common.formsAndManual,
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "d2_extension_transcript_attendance",
    visaType: "D-2",
    stayAction: "extension",
    applicantContext: "degree",
    documentType: "transcript_or_attendance",
    labelKo: "성적/출석 증빙",
    labelEn: "Transcript or attendance proof",
    validityDays: 30,
    issuer: "university",
    requiredFields: [
      field("student_name", "학생 성명", "Student name"),
      field("semester", "학기", "Semester"),
      field("academic_status", "학업 상태", "Academic status"),
    ],
    sourceRefs: common.formsAndManual,
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "d2_extension_financial_proof",
    visaType: "D-2",
    stayAction: "extension",
    applicantContext: "degree",
    documentType: "financial_proof",
    labelKo: "체류경비 입증서류",
    labelEn: "Proof of stay expenses",
    validityDays: 90,
    issuer: "bank_or_sponsor",
    requiredFields: [
      field("holder_name", "예금주", "Account holder"),
      field("balance", "잔액", "Balance"),
      field("issue_date", "발급일", "Issue date"),
    ],
    sourceRefs: common.formsAndManual,
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "d2_extension_residence_proof",
    visaType: "D-2",
    stayAction: "extension",
    applicantContext: "general",
    documentType: "residence_proof",
    labelKo: "체류지 입증서류",
    labelEn: "Proof of residence",
    validityDays: null,
    issuer: "landlord_school_or_public_authority",
    requiredFields: [
      field("address", "주소", "Address"),
      field("occupant_name", "거주자 성명", "Occupant name"),
    ],
    sourceRefs: [HIKOREA_FORMS, HIKOREA_MANUAL],
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "d4_extension_integrated_application",
    visaType: "D-4",
    stayAction: "extension",
    applicantContext: "language_training",
    documentType: "integrated_application_form",
    labelKo: "통합신청서",
    labelEn: "Integrated application form",
    validityDays: null,
    issuer: "applicant",
    requiredFields: [
      field("alien_registration_no", "외국인등록번호", "Alien registration number"),
      field("stay_action", "신청 업무", "Stay action"),
    ],
    sourceRefs: common.formsAndManual,
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "d4_extension_passport_arc",
    visaType: "D-4",
    stayAction: "extension",
    applicantContext: "language_training",
    documentType: "passport_arc",
    labelKo: "여권 및 외국인등록증",
    labelEn: "Passport and alien registration card",
    validityDays: null,
    issuer: "applicant_home_country_and_moj",
    requiredFields: [
      field("passport_no", "여권번호", "Passport number"),
      field("alien_registration_no", "외국인등록번호", "Alien registration number"),
    ],
    sourceRefs: common.formsAndManual,
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "d4_extension_enrollment_certificate",
    visaType: "D-4",
    stayAction: "extension",
    applicantContext: "language_training",
    documentType: "enrollment_certificate",
    labelKo: "재학/연수 증명서",
    labelEn: "Enrollment or training certificate",
    validityDays: 30,
    issuer: "language_institute",
    requiredFields: [
      field("student_name", "학생 성명", "Student name"),
      field("training_period", "연수 기간", "Training period"),
      field("enrollment_status", "재학 상태", "Enrollment status"),
    ],
    sourceRefs: common.formsAndManual,
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "d4_extension_attendance_certificate",
    visaType: "D-4",
    stayAction: "extension",
    applicantContext: "language_training",
    documentType: "attendance_certificate",
    labelKo: "출석증명서",
    labelEn: "Attendance certificate",
    validityDays: 30,
    issuer: "language_institute",
    requiredFields: [
      field("student_name", "학생 성명", "Student name"),
      field("attendance_rate", "출석률", "Attendance rate"),
      field("period", "대상 기간", "Covered period"),
    ],
    sourceRefs: common.formsAndManual,
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "d4_extension_financial_proof",
    visaType: "D-4",
    stayAction: "extension",
    applicantContext: "language_training",
    documentType: "financial_proof",
    labelKo: "체류경비 입증서류",
    labelEn: "Proof of stay expenses",
    validityDays: 90,
    issuer: "bank_or_sponsor",
    requiredFields: [
      field("holder_name", "예금주", "Account holder"),
      field("balance", "잔액", "Balance"),
      field("issue_date", "발급일", "Issue date"),
    ],
    sourceRefs: common.formsAndManual,
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "d4_extension_tuition_receipt",
    visaType: "D-4",
    stayAction: "extension",
    applicantContext: "language_training",
    documentType: "tuition_payment_receipt",
    labelKo: "등록금 납입 증명",
    labelEn: "Tuition payment receipt",
    validityDays: null,
    issuer: "language_institute",
    requiredFields: [
      field("student_name", "학생 성명", "Student name"),
      field("paid_amount", "납입액", "Paid amount"),
      field("covered_period", "대상 기간", "Covered period"),
    ],
    sourceRefs: [HIKOREA_MANUAL, STUDY_DOCS],
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "d4_to_d2_change_integrated_application",
    visaType: "D-2",
    stayAction: "change",
    applicantContext: "d4_to_d2",
    documentType: "integrated_application_form",
    labelKo: "통합신청서",
    labelEn: "Integrated application form",
    validityDays: null,
    issuer: "applicant",
    requiredFields: [
      field("current_status", "현재 체류자격", "Current status"),
      field("requested_status", "변경 체류자격", "Requested status"),
    ],
    sourceRefs: common.formsAndManual,
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "d4_to_d2_change_standard_admission_letter",
    visaType: "D-2",
    stayAction: "change",
    applicantContext: "d4_to_d2",
    documentType: "standard_admission_letter",
    labelKo: "표준입학허가서",
    labelEn: "Standard admission letter",
    validityDays: null,
    issuer: "receiving_university",
    requiredFields: [
      field("student_name", "학생 성명", "Student name"),
      field("program", "과정", "Program"),
      field("admission_period", "입학 기간", "Admission period"),
    ],
    sourceRefs: common.formsAndManual,
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "d4_to_d2_change_attendance",
    visaType: "D-2",
    stayAction: "change",
    applicantContext: "d4_to_d2",
    documentType: "d4_attendance_certificate",
    labelKo: "D-4 연수 출석 증빙",
    labelEn: "D-4 attendance proof",
    validityDays: 30,
    issuer: "language_institute",
    requiredFields: [
      field("student_name", "학생 성명", "Student name"),
      field("attendance_rate", "출석률", "Attendance rate"),
      field("training_period", "연수 기간", "Training period"),
    ],
    sourceRefs: common.formsAndManual,
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "d4_to_d2_change_progress",
    visaType: "D-2",
    stayAction: "change",
    applicantContext: "d4_to_d2",
    documentType: "d4_completion_or_transcript",
    labelKo: "D-4 학업 진척 증빙",
    labelEn: "D-4 study progress proof",
    validityDays: 30,
    issuer: "language_institute",
    requiredFields: [
      field("student_name", "학생 성명", "Student name"),
      field("level_or_grade", "등급/성적", "Level or grade"),
    ],
    sourceRefs: common.formsAndManual,
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "d4_to_d2_change_financial_proof",
    visaType: "D-2",
    stayAction: "change",
    applicantContext: "d4_to_d2",
    documentType: "financial_proof",
    labelKo: "재정능력 입증서류",
    labelEn: "Financial proof",
    validityDays: 90,
    issuer: "bank_or_sponsor",
    requiredFields: [
      field("holder_name", "예금주", "Account holder"),
      field("balance", "잔액", "Balance"),
      field("issue_date", "발급일", "Issue date"),
    ],
    sourceRefs: common.formsAndManual,
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "d4_to_d2_change_residence_proof",
    visaType: "D-2",
    stayAction: "change",
    applicantContext: "d4_to_d2",
    documentType: "residence_proof",
    labelKo: "체류지 입증서류",
    labelEn: "Proof of residence",
    validityDays: null,
    issuer: "landlord_school_or_public_authority",
    requiredFields: [
      field("address", "주소", "Address"),
      field("occupant_name", "거주자 성명", "Occupant name"),
    ],
    sourceRefs: [HIKOREA_FORMS, HIKOREA_MANUAL],
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "d10_change_integrated_application",
    visaType: "D-10",
    stayAction: "change",
    applicantContext: "job_seeking",
    documentType: "integrated_application_form",
    labelKo: "통합신청서",
    labelEn: "Integrated application form",
    validityDays: null,
    issuer: "applicant",
    requiredFields: [
      field("current_status", "현재 체류자격", "Current status"),
      field("requested_status", "변경 체류자격", "Requested status"),
    ],
    sourceRefs: common.formsAndManual,
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "d10_change_graduation_certificate",
    visaType: "D-10",
    stayAction: "change",
    applicantContext: "job_seeking",
    documentType: "graduation_certificate",
    labelKo: "졸업/수료 증명",
    labelEn: "Graduation or completion certificate",
    validityDays: 30,
    issuer: "university",
    requiredFields: [
      field("student_name", "학생 성명", "Student name"),
      field("graduation_date", "졸업/수료일", "Graduation or completion date"),
    ],
    sourceRefs: [HIKOREA_MANUAL, VISA_PORTAL],
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "d10_change_job_seeking_plan",
    visaType: "D-10",
    stayAction: "change",
    applicantContext: "job_seeking",
    documentType: "job_seeking_plan",
    labelKo: "구직활동계획서",
    labelEn: "Job seeking plan",
    validityDays: null,
    issuer: "applicant",
    requiredFields: [
      field("career_goal", "취업 목표", "Career goal"),
      field("activity_plan", "활동 계획", "Activity plan"),
    ],
    sourceRefs: [HIKOREA_MANUAL, VISA_PORTAL],
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "d10_change_financial_proof",
    visaType: "D-10",
    stayAction: "change",
    applicantContext: "job_seeking",
    documentType: "financial_proof",
    labelKo: "체류경비 입증서류",
    labelEn: "Proof of stay expenses",
    validityDays: 90,
    issuer: "bank_or_sponsor",
    requiredFields: [
      field("holder_name", "예금주", "Account holder"),
      field("balance", "잔액", "Balance"),
      field("issue_date", "발급일", "Issue date"),
    ],
    sourceRefs: [HIKOREA_MANUAL, VISA_PORTAL],
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "d10_change_residence_proof",
    visaType: "D-10",
    stayAction: "change",
    applicantContext: "job_seeking",
    documentType: "residence_proof",
    labelKo: "체류지 입증서류",
    labelEn: "Proof of residence",
    validityDays: null,
    issuer: "landlord_school_or_public_authority",
    requiredFields: [
      field("address", "주소", "Address"),
      field("occupant_name", "거주자 성명", "Occupant name"),
    ],
    sourceRefs: [HIKOREA_FORMS, HIKOREA_MANUAL],
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "e7_change_employment_contract",
    visaType: "E-7",
    stayAction: "change",
    applicantContext: "specific_activity",
    documentType: "employment_contract",
    labelKo: "고용계약서",
    labelEn: "Employment contract",
    validityDays: null,
    issuer: "employer",
    requiredFields: [
      field("employee_name", "근로자 성명", "Employee name"),
      field("employer_name", "고용주", "Employer"),
      field("job_title", "직무", "Job title"),
      field("wage", "임금", "Wage"),
    ],
    sourceRefs: [HIKOREA_MANUAL, VISA_PORTAL],
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "e7_change_business_registration",
    visaType: "E-7",
    stayAction: "change",
    applicantContext: "specific_activity",
    documentType: "employer_business_registration",
    labelKo: "사업자등록증",
    labelEn: "Employer business registration",
    validityDays: 90,
    issuer: "employer_or_tax_authority",
    requiredFields: [
      field("business_no", "사업자등록번호", "Business registration number"),
      field("company_name", "상호", "Company name"),
      field("industry_code", "업종", "Industry"),
    ],
    sourceRefs: [HIKOREA_MANUAL, VISA_PORTAL],
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "e7_change_job_description",
    visaType: "E-7",
    stayAction: "change",
    applicantContext: "specific_activity",
    documentType: "job_description",
    labelKo: "직무기술서",
    labelEn: "Job description",
    validityDays: null,
    issuer: "employer",
    requiredFields: [
      field("job_title", "직무", "Job title"),
      field("duties", "담당업무", "Duties"),
      field("required_qualification", "자격요건", "Required qualification"),
    ],
    sourceRefs: [HIKOREA_MANUAL, VISA_PORTAL],
    sourceUrl: "https://www.hikorea.go.kr",
    validationRules: rulesFor(
      [field("job_title", "직무", "Job title"), field("duties", "담당업무", "Duties"), field("required_qualification", "자격요건", "Required qualification")],
      null,
      ["cross_check:job_description:visa_occupation"]
    ),
  }),
  req({
    code: "e7_change_degree_or_career",
    visaType: "E-7",
    stayAction: "change",
    applicantContext: "specific_activity",
    documentType: "degree_or_career_certificate",
    labelKo: "학위/경력 증빙",
    labelEn: "Degree or career certificate",
    validityDays: null,
    issuer: "university_or_previous_employer",
    requiredFields: [
      field("applicant_name", "신청인", "Applicant"),
      field("degree_or_position", "학위/직위", "Degree or position"),
      field("period", "기간", "Period"),
    ],
    sourceRefs: [HIKOREA_MANUAL, VISA_PORTAL],
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "f2_change_integrated_application",
    visaType: "F-2",
    stayAction: "change",
    applicantContext: "residence",
    documentType: "integrated_application_form",
    labelKo: "통합신청서",
    labelEn: "Integrated application form",
    validityDays: null,
    issuer: "applicant",
    requiredFields: [
      field("current_status", "현재 체류자격", "Current status"),
      field("requested_status", "변경 체류자격", "Requested status"),
    ],
    sourceRefs: common.formsAndManual,
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "f2_change_income_tax_certificate",
    visaType: "F-2",
    stayAction: "change",
    applicantContext: "residence",
    documentType: "income_tax_certificate",
    labelKo: "소득/납세 증빙",
    labelEn: "Income or tax proof",
    validityDays: 90,
    issuer: "tax_authority_or_employer",
    requiredFields: [
      field("applicant_name", "신청인", "Applicant"),
      field("income_amount", "소득금액", "Income amount"),
      field("tax_year", "과세연도", "Tax year"),
    ],
    sourceRefs: [HIKOREA_MANUAL, VISA_PORTAL],
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "f2_change_residence_proof",
    visaType: "F-2",
    stayAction: "change",
    applicantContext: "residence",
    documentType: "residence_proof",
    labelKo: "체류지 입증서류",
    labelEn: "Proof of residence",
    validityDays: null,
    issuer: "landlord_or_public_authority",
    requiredFields: [
      field("address", "주소", "Address"),
      field("occupant_name", "거주자 성명", "Occupant name"),
    ],
    sourceRefs: [HIKOREA_FORMS, HIKOREA_MANUAL],
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "f5_permanent_residence_application_package",
    visaType: "F-5",
    stayAction: "permanent_residence",
    applicantContext: "general",
    documentType: "permanent_residence_application_package",
    labelKo: "영주자격 신청 기본서류",
    labelEn: "Permanent residence application package",
    validityDays: null,
    issuer: "applicant",
    requiredFields: [
      field("current_status", "현재 체류자격", "Current status"),
      field("residence_history", "체류 이력", "Residence history"),
      field("application_basis", "신청 근거", "Application basis"),
    ],
    sourceRefs: [LAW_STATUS_TABLE, HIKOREA_MANUAL, VISA_PORTAL],
    sourceUrl: "https://www.hikorea.go.kr",
  }),
  req({
    code: "f5_permanent_residence_criminal_record",
    visaType: "F-5",
    stayAction: "permanent_residence",
    applicantContext: "general",
    documentType: "criminal_record_or_overseas_certificate",
    labelKo: "범죄경력/해외 공적 증빙",
    labelEn: "Criminal record or overseas public certificate",
    validityDays: 180,
    issuer: "public_authority",
    requiredFields: [
      field("applicant_name", "신청인", "Applicant"),
      field("issue_date", "발급일", "Issue date"),
      field("issuing_authority", "발행기관", "Issuing authority"),
    ],
    sourceRefs: [LAW_ATTACHMENTS, HIKOREA_MANUAL, VISA_PORTAL],
    sourceUrl: "https://www.hikorea.go.kr",
    notes: "F-5 routes differ significantly; legal reviewer must confirm route-specific required documents.",
  }),
];

export function matrixCompletenessSummary(seeds: VisaDocumentRequirementSeed[] = VISA_DOCUMENT_REQUIREMENT_SEEDS) {
  const uniqueCodes = new Set(seeds.map((seed) => seed.code));
  const uniqueComposite = new Set(seeds.map((seed) => [seed.visaType, seed.stayAction, seed.applicantContext, seed.documentType].join("|")));
  const validationRuleRows = seeds.filter((seed) => seed.validationRules.length > 0);
  const reviewedRows = seeds.filter((seed) => seed.reviewStatus === "APPROVED");
  const visaTypes = Array.from(new Set(seeds.map((seed) => seed.visaType))).sort();

  return {
    totalRows: seeds.length,
    uniqueCodes: uniqueCodes.size,
    uniqueCompositeRows: uniqueComposite.size,
    validationRuleRows: validationRuleRows.length,
    reviewedRows: reviewedRows.length,
    visaTypes,
  };
}
