CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA extensions;

CREATE TABLE IF NOT EXISTS public.rag_query_aliases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  locale text NOT NULL,
  category text NOT NULL DEFAULT 'general',
  term text NOT NULL,
  expansions text[] NOT NULL DEFAULT '{}'::text[],
  enabled boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT rag_query_aliases_locale_check CHECK (locale IN ('ko', 'en', 'vi', 'mn')),
  CONSTRAINT rag_query_aliases_category_check CHECK (
    category IN ('general', 'visa', 'documents', 'school', 'cost', 'warning', 'process', 'legal')
  ),
  CONSTRAINT rag_query_aliases_term_unique UNIQUE (locale, category, term)
);

ALTER TABLE public.rag_query_aliases ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS rag_query_aliases_locale_category_enabled_idx
  ON public.rag_query_aliases (locale, category, enabled);

INSERT INTO public.rag_query_aliases (locale, category, term, expansions)
VALUES
  ('ko', 'visa', '유학비자', ARRAY['학생비자', 'D-2', 'D-4', '체류자격']),
  ('ko', 'visa', '학생 비자', ARRAY['유학비자', 'D-2', 'D-4', '체류자격']),
  ('ko', 'documents', '잔고증명', ARRAY['은행잔고증명서', '재정증빙', '예금잔액증명서']),
  ('ko', 'school', '어학당', ARRAY['대학 부설 한국어 교육기관', '한국어 연수과정']),
  ('ko', 'cost', '등록금', ARRAY['학비', '수업료', 'tuition']),
  ('en', 'visa', 'student visa', ARRAY['study visa', 'D-2', 'D-4', 'status of stay']),
  ('en', 'documents', 'bank statement', ARRAY['proof of funds', 'bank balance certificate', 'financial evidence']),
  ('en', 'school', 'language school', ARRAY['university language institute', 'Korean language program']),
  ('vi', 'visa', 'visa du học', ARRAY['thị thực du học', 'D-2', 'D-4', 'tư cách lưu trú']),
  ('vi', 'documents', 'sổ tiết kiệm', ARRAY['chứng minh tài chính', 'xác nhận số dư', 'số dư ngân hàng']),
  ('vi', 'school', 'trường tiếng', ARRAY['viện ngôn ngữ', 'chương trình tiếng Hàn']),
  ('mn', 'visa', 'оюутны виз', ARRAY['суралцах виз', 'D-2', 'D-4', 'оршин суух статус']),
  ('mn', 'documents', 'банкны үлдэгдэл', ARRAY['санхүүгийн нотолгоо', 'дансны үлдэгдлийн тодорхойлолт']),
  ('mn', 'school', 'хэлний сургууль', ARRAY['их сургуулийн хэлний бэлтгэл', 'солонгос хэлний хөтөлбөр'])
ON CONFLICT (locale, category, term) DO UPDATE
SET expansions = EXCLUDED.expansions,
    enabled = true,
    updated_at = now();

CREATE OR REPLACE FUNCTION public.kaxi_rag_normalize_search_text(value text)
RETURNS text
LANGUAGE sql
STABLE
PARALLEL SAFE
SET search_path = public, extensions
AS $$
  SELECT trim(regexp_replace(
    regexp_replace(
      lower(extensions.unaccent(coalesce(value, ''))),
      '([cdef])[[:space:]-]*([0-9]+)',
      '\1\2',
      'gi'
    ),
    '[^[:alnum:]]+',
    ' ',
    'g'
  ))
$$;

CREATE OR REPLACE FUNCTION public.kaxi_rag_compact_search_text(value text)
RETURNS text
LANGUAGE sql
STABLE
PARALLEL SAFE
SET search_path = public, extensions
AS $$
  SELECT regexp_replace(public.kaxi_rag_normalize_search_text(value), '[[:space:][:punct:]]+', '', 'g')
$$;

CREATE OR REPLACE FUNCTION public.kaxi_safe_jsonb_text_array(value text)
RETURNS SETOF text
LANGUAGE plpgsql
STABLE
PARALLEL SAFE
AS $$
DECLARE
  parsed jsonb;
BEGIN
  parsed := value::jsonb;
  IF jsonb_typeof(parsed) <> 'array' THEN
    RETURN;
  END IF;
  RETURN QUERY SELECT jsonb_array_elements_text(parsed);
EXCEPTION
  WHEN others THEN
    RETURN;
END;
$$;

CREATE OR REPLACE FUNCTION public.kaxi_expand_rag_query(
  query_text text,
  requested_category text,
  requested_locale text
)
RETURNS text
LANGUAGE plpgsql
STABLE
SET search_path = public, extensions
AS $$
DECLARE
  normalized_query text := public.kaxi_rag_normalize_search_text(query_text);
  compact_query text := public.kaxi_rag_compact_search_text(query_text);
  normalized_category text := lower(coalesce(nullif(trim(requested_category), ''), 'general'));
  normalized_locale text := coalesce(public.kaxi_normalize_rag_locale(requested_locale), 'ko');
  expansion_text text;
BEGIN
  WITH alias_matches AS (
    SELECT unnest(alias.expansions) AS term
    FROM public.rag_query_aliases alias
    WHERE alias.enabled = true
      AND alias.locale = normalized_locale
      AND (normalized_category = 'general' OR alias.category IN ('general', normalized_category))
      AND (
        position(public.kaxi_rag_normalize_search_text(alias.term) IN normalized_query) > 0
        OR position(public.kaxi_rag_compact_search_text(alias.term) IN compact_query) > 0
      )
  ),
  legacy_matches AS (
    SELECT terms.term
    FROM "Synonym" synonym
    CROSS JOIN LATERAL (
      SELECT synonym.source AS term
      UNION ALL
      SELECT target
      FROM public.kaxi_safe_jsonb_text_array(synonym.targets) AS target
    ) terms
    WHERE synonym.enabled = true
      AND (normalized_category = 'general' OR lower(synonym.category) IN ('general', normalized_category))
      AND (
        position(public.kaxi_rag_normalize_search_text(synonym.source) IN normalized_query) > 0
        OR position(public.kaxi_rag_compact_search_text(synonym.source) IN compact_query) > 0
      )
  ),
  combined AS (
    SELECT term FROM alias_matches
    UNION
    SELECT term FROM legacy_matches
  )
  SELECT string_agg(DISTINCT nullif(trim(term), ''), ' ')
  INTO expansion_text
  FROM combined
  WHERE nullif(trim(term), '') IS NOT NULL;

  RETURN left(concat_ws(' ', nullif(trim(query_text), ''), expansion_text), 4000);
END;
$$;

CREATE OR REPLACE FUNCTION public.kaxi_or_prefix_tsquery(query_text text)
RETURNS tsquery
LANGUAGE plpgsql
STABLE
SET search_path = public, extensions
AS $$
DECLARE
  normalized_query text := public.kaxi_rag_normalize_search_text(query_text);
  parsed_query text;
BEGIN
  SELECT string_agg(quote_literal(token) || ':*', ' | ')
  INTO parsed_query
  FROM (
    SELECT DISTINCT token
    FROM regexp_split_to_table(normalized_query, '[[:space:][:punct:]]+') AS token
    WHERE char_length(token) >= 2
    LIMIT 48
  ) tokens;

  IF parsed_query IS NULL OR parsed_query = '' THEN
    RETURN NULL;
  END IF;
  RETURN to_tsquery('simple', parsed_query);
EXCEPTION
  WHEN others THEN
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.match_rag_documents_lexical(
  match_count integer DEFAULT 6,
  filter jsonb DEFAULT '{}'::jsonb
)
RETURNS TABLE (
  id bigint,
  content text,
  metadata jsonb,
  similarity double precision
)
LANGUAGE plpgsql
STABLE
SET search_path = public, extensions
AS $$
DECLARE
  v_filter jsonb := coalesce(filter, '{}'::jsonb);
  v_metadata_filter jsonb := coalesce(filter, '{}'::jsonb)
    - 'query_text' - 'category' - 'category_mode' - 'tenant_id'
    - 'locale' - 'language' - 'retrieval_mode' - 'shadow_mode';
  v_query_text text := nullif(trim(coalesce(filter->>'query_text', '')), '');
  v_category text := lower(nullif(trim(coalesce(filter->>'category', '')), ''));
  v_category_mode text := lower(coalesce(nullif(trim(filter->>'category_mode'), ''), 'strict'));
  v_tenant_id text := coalesce(nullif(trim(coalesce(filter->>'tenant_id', '')), ''), 'default');
  v_locale text := public.kaxi_normalize_rag_locale(coalesce(filter->>'locale', filter->>'language'));
  v_match_count integer := greatest(least(coalesce(match_count, 6), 50), 0);
BEGIN
  IF v_query_text IS NULL THEN
    RETURN;
  END IF;
  IF v_category IN ('', 'all', 'undefined', 'null', '{{category}}') THEN
    v_category := NULL;
  END IF;
  IF v_category_mode NOT IN ('strict', 'soft', 'off') THEN
    v_category_mode := 'strict';
  END IF;
  IF v_locale IS NULL THEN
    v_locale := public.kaxi_detect_rag_text_locale(v_query_text);
  END IF;

  RETURN QUERY
  WITH query_input AS (
    SELECT
      public.kaxi_expand_rag_query(v_query_text, coalesce(v_category, 'general'), v_locale) AS expanded_query,
      public.kaxi_rag_normalize_search_text(v_query_text) AS query_normalized,
      public.kaxi_rag_compact_search_text(v_query_text) AS query_compact
  ),
  q AS (
    SELECT
      query_input.*,
      public.kaxi_or_prefix_tsquery(query_input.expanded_query) AS tsq
    FROM query_input
  ),
  eligible AS (
    SELECT
      serving.*,
      localized.localized_content,
      coalesce(
        nullif(
          trim(regexp_replace(split_part(localized.localized_content, E'\n', 1), '^#{1,6}[[:space:]]+', '')),
          ''
        ),
        document.title
      ) AS localized_title,
      document.title AS canonical_title,
      document."sourceUrl" AS canonical_source_url,
      document."sourceType" AS canonical_source_type,
      document.language AS canonical_language,
      document.topic AS canonical_topic,
      document."lastCheckedAt" AS canonical_checked_at,
      document."checkedBy" AS canonical_checked_by
    FROM public.rag_serving_chunks serving
    JOIN "KnowledgeChunk" chunk
      ON chunk.id = serving.canonical_chunk_id
      AND chunk."contentHash" = serving.content_hash
    JOIN "KnowledgeDocument" document
      ON document.id = serving.canonical_document_id
      AND document.id = chunk."documentId"
      AND document."docId" = serving.doc_id
    CROSS JOIN LATERAL (
      SELECT public.kaxi_extract_rag_locale_sections(serving.content, v_locale) AS localized_content
    ) localized
    WHERE serving.status = 'ready'
      AND serving.tenant_id = v_tenant_id
      AND serving.metadata @> v_metadata_filter
      AND document."reviewStatus" = 'APPROVED'::"LegalReviewStatus"
      AND document."supersededBy" IS NULL
      AND document."validFrom" <= now()
      AND (document."validTo" IS NULL OR document."validTo" > now())
      AND document."lastCheckedAt" >= now() - interval '180 days'
      AND (v_locale IS NULL OR localized.localized_content IS NOT NULL)
      AND (
        v_category IS NULL
        OR v_category = 'general'
        OR v_category_mode IN ('soft', 'off')
        OR public.kaxi_rag_category_allowed(
          v_category,
          coalesce(nullif(document.topic, ''), serving.category)
        )
      )
  ),
  searchable AS (
    SELECT
      eligible.*,
      public.kaxi_rag_normalize_search_text(eligible.doc_id) AS doc_id_normalized,
      public.kaxi_rag_compact_search_text(eligible.doc_id) AS doc_id_compact,
      public.kaxi_rag_normalize_search_text(eligible.localized_title) AS title_normalized,
      public.kaxi_rag_compact_search_text(eligible.localized_title) AS title_compact,
      public.kaxi_rag_normalize_search_text(eligible.metadata->>'keywords') AS keywords_normalized,
      public.kaxi_rag_normalize_search_text(left(eligible.localized_content, 4000)) AS body_normalized,
      setweight(to_tsvector('simple', public.kaxi_rag_normalize_search_text(eligible.doc_id)), 'A')
        || setweight(to_tsvector('simple', public.kaxi_rag_normalize_search_text(eligible.localized_title)), 'A')
        || setweight(to_tsvector('simple', public.kaxi_rag_normalize_search_text(eligible.metadata->>'keywords')), 'B')
        || setweight(to_tsvector('simple', public.kaxi_rag_normalize_search_text(eligible.category)), 'C')
        || setweight(to_tsvector('simple', public.kaxi_rag_normalize_search_text(eligible.localized_content)), 'D')
        AS weighted_document
    FROM eligible
  ),
  matched AS (
    SELECT
      searchable.*,
      q.query_normalized,
      q.query_compact,
      q.tsq,
      least(coalesce(ts_rank_cd(searchable.weighted_document, q.tsq), 0) * 1.8, 0.9) AS weighted_rank_score,
      CASE
        WHEN char_length(searchable.doc_id_compact) >= 2
          AND position(searchable.doc_id_compact IN q.query_compact) > 0 THEN 0.55
        ELSE 0
      END AS exact_doc_id_score,
      CASE
        WHEN char_length(q.query_normalized) >= 4
          AND (
            position(q.query_normalized IN searchable.title_normalized) > 0
            OR position(searchable.title_normalized IN q.query_normalized) > 0
          ) THEN 0.28
        ELSE 0
      END AS exact_title_score,
      least(
        greatest(
          extensions.similarity(searchable.title_normalized, q.query_normalized),
          extensions.similarity(searchable.title_compact, q.query_compact)
        ) * 0.34,
        0.34
      ) AS title_similarity_score,
      least(extensions.similarity(searchable.body_normalized, q.query_normalized) * 0.08, 0.08)
        AS body_similarity_score,
      CASE
        WHEN searchable.canonical_source_url ~* '(law\.go\.kr|hikorea\.go\.kr|moj\.go\.kr|studyinkorea\.go\.kr)' THEN 0.14
        WHEN searchable.canonical_source_url ~* '\.go\.kr(?:/|$)' THEN 0.11
        WHEN searchable.canonical_source_url ~* '\.ac\.kr(?:/|$)' THEN 0.07
        WHEN lower(searchable.canonical_source_type) LIKE 'official%' THEN 0.09
        ELSE 0.03
      END AS source_authority_score,
      CASE
        WHEN searchable.canonical_checked_at >= now() - interval '30 days' THEN 0.08
        WHEN searchable.canonical_checked_at >= now() - interval '90 days' THEN 0.05
        ELSE 0.02
      END AS freshness_score,
      CASE
        WHEN v_category IS NULL OR v_category = 'general' OR v_category_mode = 'off' THEN 0
        WHEN lower(searchable.canonical_topic) = v_category THEN 0.08
        WHEN lower(searchable.category) = v_category THEN 0.05
        ELSE 0.02
      END AS category_score
    FROM searchable
    CROSS JOIN q
    WHERE
      (q.tsq IS NOT NULL AND searchable.weighted_document @@ q.tsq)
      OR (
        char_length(q.query_normalized) >= 4
        AND position(q.query_normalized IN concat_ws(' ', searchable.title_normalized, searchable.keywords_normalized, searchable.body_normalized)) > 0
      )
      OR extensions.similarity(searchable.title_normalized, q.query_normalized) >= 0.08
      OR (
        char_length(q.query_compact) >= 3
        AND extensions.similarity(searchable.title_compact, q.query_compact) >= 0.12
      )
      OR (
        char_length(searchable.doc_id_compact) >= 2
        AND position(searchable.doc_id_compact IN q.query_compact) > 0
      )
  ),
  ranked AS (
    SELECT
      matched.*,
      matched.weighted_rank_score
        + matched.exact_doc_id_score
        + matched.exact_title_score
        + matched.title_similarity_score
        + matched.body_similarity_score
        + matched.source_authority_score
        + matched.freshness_score
        + matched.category_score AS lexical_score
    FROM matched
    ORDER BY lexical_score DESC, matched.id
    LIMIT v_match_count
  )
  SELECT
    ranked.id,
    ranked.localized_content AS content,
    ranked.metadata || jsonb_build_object(
      'doc_id', ranked.doc_id,
      'title', ranked.localized_title,
      'source_url', ranked.canonical_source_url,
      'source_type', ranked.canonical_source_type,
      'language', coalesce(v_locale, ranked.canonical_language),
      'category', ranked.canonical_topic,
      'last_checked_at', ranked.canonical_checked_at,
      'checked_by', ranked.canonical_checked_by,
      'review_status', 'approved',
      'citation_valid', ranked.canonical_source_url ~ '^https://',
      'retrieval_type', 'lexical-v2',
      'score_version', 'absolute-weighted-v2',
      'category_mode', v_category_mode,
      'locale_filter', v_locale,
      'query_expanded', ranked.tsq IS NOT NULL,
      'similarity_threshold', 0,
      'lexical_score', ranked.lexical_score,
      'hybrid_score', ranked.lexical_score,
      'vector_score', 0,
      'keyword_score', ranked.weighted_rank_score,
      'exact_doc_id_score', ranked.exact_doc_id_score,
      'exact_title_score', ranked.exact_title_score,
      'title_similarity_score', ranked.title_similarity_score,
      'body_similarity_score', ranked.body_similarity_score,
      'source_authority_score', ranked.source_authority_score,
      'freshness_score', ranked.freshness_score,
      'category_score', ranked.category_score
    ) AS metadata,
    ranked.lexical_score::double precision AS similarity
  FROM ranked
  ORDER BY ranked.lexical_score DESC, ranked.id;
END;
$$;

REVOKE ALL ON TABLE public.rag_query_aliases FROM PUBLIC;
REVOKE ALL ON FUNCTION public.kaxi_rag_normalize_search_text(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.kaxi_rag_compact_search_text(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.kaxi_safe_jsonb_text_array(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.kaxi_expand_rag_query(text, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.kaxi_or_prefix_tsquery(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.match_rag_documents_lexical(integer, jsonb) FROM PUBLIC;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON TABLE public.rag_query_aliases FROM anon;
    REVOKE ALL ON FUNCTION public.kaxi_rag_normalize_search_text(text) FROM anon;
    REVOKE ALL ON FUNCTION public.kaxi_rag_compact_search_text(text) FROM anon;
    REVOKE ALL ON FUNCTION public.kaxi_safe_jsonb_text_array(text) FROM anon;
    REVOKE ALL ON FUNCTION public.kaxi_expand_rag_query(text, text, text) FROM anon;
    REVOKE ALL ON FUNCTION public.kaxi_or_prefix_tsquery(text) FROM anon;
    REVOKE ALL ON FUNCTION public.match_rag_documents_lexical(integer, jsonb) FROM anon;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    REVOKE ALL ON TABLE public.rag_query_aliases FROM authenticated;
    REVOKE ALL ON FUNCTION public.kaxi_rag_normalize_search_text(text) FROM authenticated;
    REVOKE ALL ON FUNCTION public.kaxi_rag_compact_search_text(text) FROM authenticated;
    REVOKE ALL ON FUNCTION public.kaxi_safe_jsonb_text_array(text) FROM authenticated;
    REVOKE ALL ON FUNCTION public.kaxi_expand_rag_query(text, text, text) FROM authenticated;
    REVOKE ALL ON FUNCTION public.kaxi_or_prefix_tsquery(text) FROM authenticated;
    REVOKE ALL ON FUNCTION public.match_rag_documents_lexical(integer, jsonb) FROM authenticated;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    GRANT SELECT ON TABLE public.rag_query_aliases TO service_role;
    GRANT EXECUTE ON FUNCTION public.kaxi_rag_normalize_search_text(text) TO service_role;
    GRANT EXECUTE ON FUNCTION public.kaxi_rag_compact_search_text(text) TO service_role;
    GRANT EXECUTE ON FUNCTION public.kaxi_safe_jsonb_text_array(text) TO service_role;
    GRANT EXECUTE ON FUNCTION public.kaxi_expand_rag_query(text, text, text) TO service_role;
    GRANT EXECUTE ON FUNCTION public.kaxi_or_prefix_tsquery(text) TO service_role;
    GRANT EXECUTE ON FUNCTION public.match_rag_documents_lexical(integer, jsonb) TO service_role;
  END IF;
END
$$;

COMMENT ON TABLE public.rag_query_aliases IS
  'Locale and category scoped RAG aliases used by lexical and hybrid retrieval.';
COMMENT ON FUNCTION public.match_rag_documents_lexical(integer, jsonb) IS
  'Lexical v2 retrieval with strict locale/category policy, weighted fields, DB aliases, unaccent normalization, typo tolerance, authority, and freshness scoring.';

NOTIFY pgrst, 'reload schema';
