import type { KnowledgeDoc, SourceType } from "../data/knowledge";

export type OfficialEvidenceKind =
  | "government_guidance"
  | "official_qna"
  | "court_decision"
  | "enforcement_case"
  | "consular_guidance";

export interface VerifiedOfficialKnowledgeSource {
  docId: string;
  title: string;
  sourceUrl: string;
  sourceType: SourceType;
  topic: KnowledgeDoc["category"];
  language?: string;
  jurisdiction?: "KR" | "KAXI";
  legalPriority?: 1 | 2 | 3 | 4;
  monitorCadence?: "daily" | "weekly" | "monthly";
  changeSignals?: string[];
  evidenceKind?: OfficialEvidenceKind;
  applicantRegion?: string;
  requiredContentSignals?: string[];
  minimumExtractedChars?: number;
}

const EASYLAW_BASE = "https://www.easylaw.go.kr/CSP";
const S_COURT_BASE = "https://www.scourt.go.kr";
const MOFA_BASE = "https://overseas.mofa.go.kr";

// These sources are bounded to official Korean government and court hosts. They are
// harvested as PENDING candidates and require the normal legal-review promotion gate.
export const VERIFIED_OFFICIAL_KNOWLEDGE_SOURCES: VerifiedOfficialKnowledgeSource[] = [
  {
    docId: "easylaw-foreign-student-guide",
    title: "찾기쉬운 생활법령 외국인유학생 안내",
    sourceUrl: `${EASYLAW_BASE}/CsmMainBtr.laf?csmSeq=508`,
    sourceType: "official_government",
    topic: "visa",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "government_guidance",
    changeSignals: ["d2", "d4", "foreign_student", "stay", "registration"],
    requiredContentSignals: ["외국인유학생", "유학(D-2)", "일반연수(D-4)"],
    minimumExtractedChars: 700,
  },
  {
    docId: "easylaw-foreign-student-part-time-work",
    title: "찾기쉬운 생활법령 외국인유학생 시간제취업",
    sourceUrl: "https://m.easylaw.go.kr/MOB/CsmInfoRetrieve.laf?ccfNo=3&cciNo=6&cnpClsNo=1&csmSeq=2853",
    sourceType: "official_government",
    topic: "process",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "government_guidance",
    changeSignals: ["part_time_work", "d2", "d4", "permission", "korean_proficiency"],
    requiredContentSignals: ["시간제 취업", "아르바이트", "D-2", "D-4"],
    minimumExtractedChars: 700,
  },
  {
    docId: "easylaw-foreign-worker-employment-guide",
    title: "찾기쉬운 생활법령 외국인근로자 취업 안내",
    sourceUrl: `${EASYLAW_BASE}/CsmMainBtr.laf?csmSeq=2042`,
    sourceType: "official_government",
    topic: "visa",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "government_guidance",
    changeSignals: ["e9", "h2", "employment_permit", "workplace_change", "reentry"],
    requiredContentSignals: ["외국인근로자", "비전문취업(E-9)", "방문취업(H-2)"],
    minimumExtractedChars: 700,
  },
  {
    docId: "easylaw-foreign-worker-status-methods",
    title: "찾기쉬운 생활법령 체류자격별 취업방법",
    sourceUrl: `${EASYLAW_BASE}/CnpClsMain.laf?ccfNo=1&cciNo=1&cnpClsNo=2&csmSeq=2042`,
    sourceType: "official_government",
    topic: "visa",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "government_guidance",
    changeSignals: ["work_status", "e9", "h2", "f4", "permitted_industry"],
    requiredContentSignals: ["체류자격별 취업방법", "E-9", "H-2"],
    minimumExtractedChars: 900,
  },
  {
    docId: "easylaw-foreign-worker-workplace-change",
    title: "찾기쉬운 생활법령 외국인근로자 사업장 변경",
    sourceUrl: `${EASYLAW_BASE}/CnpClsMain.laf?ccfNo=3&cciNo=2&cnpClsNo=1&csmSeq=2042&popMenu=ov`,
    sourceType: "official_government",
    topic: "process",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "government_guidance",
    changeSignals: ["workplace_change", "e9", "employer_fault", "application_limit"],
    requiredContentSignals: ["근무처", "사업장", "E-9"],
    minimumExtractedChars: 900,
  },
  {
    docId: "easylaw-marriage-immigrant-status",
    title: "찾기쉬운 생활법령 결혼이민 F-6 체류자격",
    sourceUrl: `${EASYLAW_BASE}/CnpClsMain.laf?ccfNo=2&cciNo=1&cnpClsNo=1&csmSeq=47&popMenu=ov`,
    sourceType: "official_government",
    topic: "visa",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "government_guidance",
    changeSignals: ["f6", "marriage_immigrant", "invitation", "permanent_residence"],
    requiredContentSignals: ["결혼이민", "F-6", "체류자격"],
    minimumExtractedChars: 900,
  },
  {
    docId: "easylaw-marriage-immigrant-reentry",
    title: "찾기쉬운 생활법령 결혼이민자 가족방문·재입국",
    sourceUrl: `${EASYLAW_BASE}/CnpClsMain.laf?ccfNo=3&cciNo=3&cnpClsNo=2&csmSeq=47`,
    sourceType: "official_government",
    topic: "process",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "government_guidance",
    changeSignals: ["reentry", "f6", "family_visit", "single_visa"],
    requiredContentSignals: ["재입국", "결혼이민", "F-6"],
    minimumExtractedChars: 700,
  },
  {
    docId: "easylaw-marriage-immigrant-official-qna",
    title: "찾기쉬운 생활법령 결혼이민 체류 국민신문고 Q&A",
    sourceUrl: `${EASYLAW_BASE}/CnpClsMain.laf?ccfNo=2&cciNo=1&cnpClsNo=1&csmSeq=47&menuType=qna`,
    sourceType: "official_government",
    topic: "legal",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "official_qna",
    changeSignals: ["official_qna", "f6", "f5_spouse", "consular_discretion"],
    requiredContentSignals: ["국민신문고", "F-6", "체류"],
    minimumExtractedChars: 600,
  },
  {
    docId: "easylaw-overseas-korean-f4-status",
    title: "찾기쉬운 생활법령 재외동포 F-4 출입국·체류",
    sourceUrl: `${EASYLAW_BASE}/CnpClsMainBtr.laf?ccfNo=3&cciNo=2&cnpClsNo=2&csmSeq=1136`,
    sourceType: "official_government",
    topic: "visa",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "government_guidance",
    changeSignals: ["f4", "overseas_korean", "domestic_residence", "visa_application"],
    requiredContentSignals: ["재외동포", "F-4", "체류자격"],
    minimumExtractedChars: 900,
  },
  {
    docId: "easylaw-overseas-korean-employment",
    title: "찾기쉬운 생활법령 재외동포 F-4 국내취업 범위",
    sourceUrl: `${EASYLAW_BASE}/CnpClsMainBtr.laf?ccfNo=3&cciNo=3&cnpClsNo=1&csmSeq=1136`,
    sourceType: "official_government",
    topic: "warning",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "government_guidance",
    changeSignals: ["f4", "employment_scope", "simple_labor", "restricted_industry"],
    requiredContentSignals: ["재외동포", "F-4", "취업"],
    minimumExtractedChars: 900,
  },
  {
    docId: "scourt-f4-visa-refusal-2017du38874",
    title: "대법원 2017두38874 사증발급 거부처분 판결",
    sourceUrl: `${S_COURT_BASE}/portal/news/NewsViewAction.work?gubun=4&searchOption=&searchWord=&seqnum=6732`,
    sourceType: "official_government",
    topic: "legal",
    legalPriority: 2,
    monitorCadence: "monthly",
    evidenceKind: "court_decision",
    changeSignals: ["f4", "visa_refusal", "entry_ban", "administrative_discretion"],
    requiredContentSignals: ["2017두38874", "사증발급", "재외동포"],
    minimumExtractedChars: 1200,
  },
  {
    docId: "scourt-f4-second-refusal-2020guhap80547",
    title: "서울행정법원 2020구합80547 F-4 사증 재거부 판결",
    sourceUrl: `${S_COURT_BASE}/portal/dcboard/DcNewsViewAction.work?cbub_code=000220&gubun=44&searchOption=&searchWord=&seqnum=23910`,
    sourceType: "official_government",
    topic: "legal",
    legalPriority: 2,
    monitorCadence: "monthly",
    evidenceKind: "court_decision",
    changeSignals: ["f4", "visa_refusal", "binding_effect", "balancing"],
    requiredContentSignals: ["2020구합80547", "사증발급", "재외동포"],
    minimumExtractedChars: 1000,
  },
  {
    docId: "scourt-stay-extension-departure-order-2017guhap21137",
    title: "법원 2017구합21137 체류기간 연장불허·출국명령 판결",
    sourceUrl: `${S_COURT_BASE}/portal/dcboard/DcNewsViewAction.work?cbub_code=000310&gubun=44&searchOption=&searchWord=&seqnum=19326`,
    sourceType: "official_government",
    topic: "legal",
    legalPriority: 2,
    monitorCadence: "monthly",
    evidenceKind: "court_decision",
    changeSignals: ["stay_extension", "departure_order", "discretion", "criminal_history"],
    requiredContentSignals: ["2017구합21137", "체류기간", "출국명령"],
    minimumExtractedChars: 900,
  },
  {
    docId: "scourt-f6-visa-refusal-2014du42506",
    title: "대법원 2014두42506 F-6 사증발급 거부 판결",
    sourceUrl: `${S_COURT_BASE}/sjudge/1526545707768_172827.pdf`,
    sourceType: "official_government",
    topic: "legal",
    legalPriority: 2,
    monitorCadence: "monthly",
    evidenceKind: "court_decision",
    changeSignals: ["f6", "visa_refusal", "standing", "administrative_litigation"],
    requiredContentSignals: ["2014두42506", "사증발급", "결혼이민"],
    minimumExtractedChars: 1200,
  },
  {
    docId: "scourt-permanent-residence-cancellation-procedure",
    title: "법원 영주 체류자격 취소·출국명령 절차 판결",
    sourceUrl: `${S_COURT_BASE}/sjudge/1715585650230_163410.pdf`,
    sourceType: "official_government",
    topic: "legal",
    legalPriority: 2,
    monitorCadence: "monthly",
    evidenceKind: "court_decision",
    changeSignals: ["f5", "status_cancellation", "departure_order", "written_notice"],
    requiredContentSignals: ["영주", "체류자격", "출국명령"],
    minimumExtractedChars: 1200,
  },
  {
    docId: "scourt-f4-refusal-recent-judgment",
    title: "서울행정법원 재외동포 F-4 사증발급 불허 판결",
    sourceUrl: "https://file.scourt.go.kr/dcboard/1758162320449_112520.pdf",
    sourceType: "official_government",
    topic: "legal",
    legalPriority: 2,
    monitorCadence: "monthly",
    evidenceKind: "court_decision",
    changeSignals: ["f4", "visa_refusal", "public_interest", "consular_review"],
    requiredContentSignals: ["재외동포", "사증발급", "불허"],
    minimumExtractedChars: 1200,
  },
  {
    docId: "moj-1345-multilingual-consultation",
    title: "법무부 외국인종합안내센터 1345",
    sourceUrl: "https://www.immigration.go.kr/immigration/1530/subview.do",
    sourceType: "official_government",
    topic: "process",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "government_guidance",
    changeSignals: ["1345", "languages", "consultation_hours", "immigration_help"],
    requiredContentSignals: ["1345", "외국인종합안내센터", "출입국민원"],
    minimumExtractedChars: 700,
  },
  {
    docId: "moj-foreign-resident-legal-support",
    title: "법무부 체류외국인 무료 법률상담 연계",
    sourceUrl: "https://www.immigration.go.kr/immigration/1574/subview.do",
    sourceType: "official_government",
    topic: "process",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "government_guidance",
    changeSignals: ["village_lawyer", "1345", "legal_consultation", "interpretation"],
    requiredContentSignals: ["무료법률상담", "1345", "외국인"],
    minimumExtractedChars: 600,
  },
  {
    docId: "moj-illegal-delivery-rider-enforcement-2026",
    title: "법무부 2026 외국인 불법 배달 취업 단속 사례",
    sourceUrl: "https://www.immigration.go.kr/immigration/1502/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGaW1taWdyYXRpb24lMkYyMTQlMkY2MDgyNDAlMkZhcnRjbFZpZXcuZG8lM0Y%3D",
    sourceType: "official_government",
    topic: "warning",
    legalPriority: 3,
    monitorCadence: "monthly",
    evidenceKind: "enforcement_case",
    changeSignals: ["d2", "d10", "illegal_employment", "delivery_rider", "enforcement"],
    requiredContentSignals: ["불법 배달", "D-2", "D-10"],
    minimumExtractedChars: 800,
  },
  {
    docId: "moj-overseas-korean-f4-integration-2026",
    title: "법무부 2026 동포 체류자격 F-4 통합",
    sourceUrl: "https://www.immigration.go.kr/bbs/immigration/214/606907/artclView.do",
    sourceType: "official_government",
    topic: "visa",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "government_guidance",
    changeSignals: ["f4", "h2", "overseas_korean", "status_integration"],
    requiredContentSignals: ["재외동포", "F-4", "체류자격 통합"],
    minimumExtractedChars: 800,
  },
  {
    docId: "moj-new-immigration-policy-cases-2024",
    title: "법무부 신 출입국·이민정책 후속조치 사례",
    sourceUrl: "https://www.immigration.go.kr/bbs/moj/182/475040/download.do",
    sourceType: "official_government",
    topic: "visa",
    legalPriority: 3,
    monitorCadence: "monthly",
    evidenceKind: "government_guidance",
    changeSignals: ["e9", "e7", "regional_visa", "policy_case"],
    requiredContentSignals: ["출입국", "이민정책", "체류자격"],
    minimumExtractedChars: 1200,
  },
  {
    docId: "mofa-vietnam-student-visa-2026-ko",
    title: "주베트남대사관 2026 유학 D-2·D-4 사증 안내",
    sourceUrl: `${MOFA_BASE}/vn-ko/brd/m_2198/view.do?page=1&seq=1343485`,
    sourceType: "official_government",
    topic: "documents",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "consular_guidance",
    applicantRegion: "VN",
    changeSignals: ["d2", "d4", "required_documents", "application_form", "financial_proof"],
    requiredContentSignals: ["유학비자", "D-2", "D-4"],
    minimumExtractedChars: 500,
  },
  {
    docId: "mofa-hochiminh-student-visa-2026-ko",
    title: "주호치민총영사관 2026 유학 D-2·D-4 사증 안내",
    sourceUrl: `${MOFA_BASE}/vn-hochiminh-ko/brd/m_4020/view.do?page=2&seq=1234033`,
    sourceType: "official_government",
    topic: "documents",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "consular_guidance",
    applicantRegion: "VN-HCMC",
    changeSignals: ["d2", "d4", "required_documents", "processing_time", "tuberculosis"],
    requiredContentSignals: ["유학", "D-2", "D-4"],
    minimumExtractedChars: 600,
  },
  {
    docId: "mofa-japan-student-visa-2026-ko",
    title: "주요코하마총영사관 2026 유학 D-2·D-4 사증 안내",
    sourceUrl: `${MOFA_BASE}/jp-yokohama-ko/brd/m_909/view.do?page=1&seq=1344083`,
    sourceType: "official_government",
    topic: "documents",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "consular_guidance",
    applicantRegion: "JP-YOKOHAMA",
    changeSignals: ["d2", "d4", "required_documents", "residence_card", "certified_university"],
    requiredContentSignals: ["유학", "D-2", "D-4"],
    minimumExtractedChars: 900,
  },
  {
    docId: "mofa-vietnam-student-visa-vi",
    title: "VISA du học Hàn Quốc D-2, D-4",
    sourceUrl: `${MOFA_BASE}/vn-vi/brd/m_2156/view.do?page=1&seq=681710`,
    sourceType: "official_government",
    topic: "documents",
    language: "vi",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "consular_guidance",
    applicantRegion: "VN",
    changeSignals: ["d2", "d4", "ho_so", "tai_chinh", "tuberculosis"],
    requiredContentSignals: ["VISA DU HỌC", "D-2", "D-4"],
    minimumExtractedChars: 1200,
  },
  {
    docId: "mofa-hochiminh-student-visa-vi",
    title: "VISA DU HỌC D-2, D-4 tại Thành phố Hồ Chí Minh",
    sourceUrl: `${MOFA_BASE}/vn-hochiminh-vi/brd/m_3360/view.do?page=1&seq=6`,
    sourceType: "official_government",
    topic: "documents",
    language: "vi",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "consular_guidance",
    applicantRegion: "VN-HCMC",
    changeSignals: ["d2", "d4", "ho_so", "consulate"],
    requiredContentSignals: ["VISA DU HỌC", "D-2", "D-4"],
    minimumExtractedChars: 400,
  },
  {
    docId: "mofa-mongolia-visa-process-mn",
    title: "Виз мэдүүлэхэд бүрдүүлэх материалын журам",
    sourceUrl: `${MOFA_BASE}/mn-mn/brd/m_288/view.do?page=1&seq=758314`,
    sourceType: "official_government",
    topic: "process",
    language: "mn",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "consular_guidance",
    applicantRegion: "MN",
    changeSignals: ["visa_process", "required_documents", "visa_finder", "embassy_notice"],
    requiredContentSignals: ["Виз мэдүүлэхэд", "материалын журам", "VISA FINDER"],
    minimumExtractedChars: 400,
  },
  {
    docId: "mofa-malaysia-d2-visa-2026-en",
    title: "Malaysia D-2 Student Visa Requirements",
    sourceUrl: `${MOFA_BASE}/my-en/brd/m_26576/view.do?page=1&seq=9`,
    sourceType: "official_government",
    topic: "documents",
    language: "en",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "consular_guidance",
    applicantRegion: "MY",
    changeSignals: ["d2", "required_documents", "financial_proof", "tuberculosis"],
    requiredContentSignals: ["D-2", "STUDENT VISA", "Eligible Applicants"],
    minimumExtractedChars: 900,
  },
  {
    docId: "mofa-finland-d2-visa-2026-en",
    title: "Finland D-2 Student Visa Requirements",
    sourceUrl: `${MOFA_BASE}/fi-en/brd/m_20979/view.do?seq=3`,
    sourceType: "official_government",
    topic: "documents",
    language: "en",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "consular_guidance",
    applicantRegion: "FI",
    changeSignals: ["d2", "reservation", "processing_time", "required_documents"],
    requiredContentSignals: ["D-2", "Student", "Visa"],
    minimumExtractedChars: 700,
  },
  {
    docId: "mofa-singapore-d2-visa-2025-en",
    title: "Singapore D-2 Student Visa Requirements",
    sourceUrl: `${MOFA_BASE}/sg-en/brd/m_2444/view.do?page=2&seq=761428`,
    sourceType: "official_government",
    topic: "documents",
    language: "en",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "consular_guidance",
    applicantRegion: "SG",
    changeSignals: ["d2", "application", "required_documents", "reentry"],
    requiredContentSignals: ["D-2", "Student Visa", "How to apply"],
    minimumExtractedChars: 900,
  },
  {
    docId: "mofa-seattle-d2-d4-visa-2026-en",
    title: "Seattle D-2 Student and D-4 Language Trainee Visa",
    sourceUrl: `${MOFA_BASE}/us-seattle-en/brd/m_23042/view.do?seq=45`,
    sourceType: "official_government",
    topic: "documents",
    language: "en",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "consular_guidance",
    applicantRegion: "US-SEATTLE",
    changeSignals: ["d2", "d4", "student_visa", "language_trainee"],
    requiredContentSignals: ["D-2", "D-4", "Visa"],
    minimumExtractedChars: 700,
  },
  {
    docId: "official-e7-employment-requirements",
    title: "하이코리아 취업의 목적(91일 이상) 특정활동(E-7) 출입국·체류 안내",
    sourceUrl: "https://www.hikorea.go.kr/info/InfoDatail.pt?CAT_SEQ=527&PARENT_ID=1278",
    sourceType: "official_government",
    topic: "visa",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "government_guidance",
    changeSignals: ["e7", "wage", "occupation"],
    requiredContentSignals: ["특정활동(E-7)", "E-7", "체류자격"],
    minimumExtractedChars: 700,
  },
  {
    docId: "official-f2-points-residency",
    title: "하이코리아 친척방문·가족동거·거주·동반·재외동포(91일 이상) 거주(F-2) 출입국·체류 안내",
    sourceUrl: "https://www.hikorea.go.kr/info/InfoDatail.pt?CAT_SEQ=616&PARENT_ID=1269",
    sourceType: "official_government",
    topic: "visa",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "government_guidance",
    changeSignals: ["f2", "points", "residency"],
    requiredContentSignals: ["거주(F-2)", "F-2", "체류자격"],
    minimumExtractedChars: 700,
  },
  {
    docId: "official-f5-permanent-residency",
    title: "하이코리아 체류자격부여 기준 안내 (영주 F-5 포함)",
    sourceUrl: "https://www.hikorea.go.kr/info/InfoDatail.pt?CAT_SEQ=191&PARENT_ID=144",
    sourceType: "official_government",
    topic: "visa",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "government_guidance",
    changeSignals: ["f5", "permanent", "routes"],
    requiredContentSignals: ["영주(F-5)", "F-5", "체류자격부여"],
    minimumExtractedChars: 700,
  },
  {
    docId: "mofa-hong-kong-d2-visa-2026-en",
    title: "Hong Kong D-2 Study Visa Requirements",
    sourceUrl: `${MOFA_BASE}/hk-en/brd/m_20261/view.do?seq=717439`,
    sourceType: "official_government",
    topic: "documents",
    language: "en",
    legalPriority: 3,
    monitorCadence: "weekly",
    evidenceKind: "consular_guidance",
    applicantRegion: "HK",
    changeSignals: ["d2", "study", "required_documents", "academic_proof"],
    requiredContentSignals: ["D-2", "Study", "Visa"],
    minimumExtractedChars: 400,
  },
];
